name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/haskell.yml
  # TODO: Release workflow #19 (https://github.com/geniusyield/atlas/issues/19)
  #       - Download artifacts
  #       - Publish artifacts as GitHub Release
