name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      name: Download source distribution file artifact
      with:
        name: source-distribution-file
        path: ./artifacts
    - name: Create release draft (GitHub)
      env:
        ATLAS_VERSION: ${{needs.build.outputs.ATLAS_VERSION}}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        SEMANTIC_VERSION=v${ATLAS_VERSION/#atlas-}
        TAGS=$(git describe --tags)
        GIT_REVISION=$(git rev-parse HEAD)
        echo "ATLAS_VERSION: ${{ env.ATLAS_VERSION }}"
        echo "SEMANTIC_VERSION: $SEMANTIC_VERSION"
        echo "TAGS: $TAGS"
        echo "GIT_REVISION: $GIT_REVISION"
        set -x
        gh release create \
          --generate-notes \
          --verify-tag \
          --draft \
          "${SEMANTIC_VERSION}" \
          "./artifacts/${{ env.ATLAS_VERSION }}.tar.gz#Source distribution file (tar.gz)"
        echo "::notice::Succesfully created release draft ${SEMANTIC_VERSION}, built from ${GIT_REVISION}. (Uploaded: ${{ env.ATLAS_VERSION }}.tar.gz)"
