name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/haskell.yml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      name: Download source distribution file
      with:
        name: source-distribution-file
        path: ./
    - uses: actions/download-artifact@v3
      name: Download haddock
      with:
        name: github-pages
        path: ./
    - name: Create release draft (GitHub)
      env:
        ATLAS_VERSION: ${{needs.build.outputs.ATLAS_VERSION}}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        echo "${{ env.ATLAS_VERSION }}"
        SEMANTIC_VERSION=v${ATLAS_VERSION/#atlas-}
        TAGS=$(git describe --tags)
        echo "SEMANTIC_VERSION: $SEMANTIC_VERSION"
        echo "TAGS: $TAGS"
        set -x
        pwd
        tree -L 3
        mv ./atlas ./atlas.zip
        mv ./github-pages ./haddock.zip
        gh release create \
          --generate-notes \
          --verify-tag \
          --draft \
          "${SEMANTIC_VERSION}" \
          "./atlas.zip#atlas ./haddock.zip#haddock"
        #unzip source-distribution-file.zip
        # Upload package candidate to hackage:
        # cabal upload \
        #   --username=${{ secrets.HACKAGE_USER }} \
        #   --password-command=${{ secrets.HACKAGE_PASSWORD }} \
        # ./${{ env.ATLAS_VERSION }}.tar.gz